version: '3'

services:

  app:
    build: '.'
    volumes:
      - '.:/app'
    ports:
      - '8000:8787'

  localhost:
    build: 
      context: '.'
      dockerfile: './Dockerfile.localhost'
    volumes:
      - '.:/app'
    ports:
      - '8000:80'
